#' Extract adjustment table
#'
#' Using a DAG information, extracts adjustment tables for
#' pre-specified (hard-coded) outcome/predictor pairs.
#'
#' @param DAG tidy_dagitty object. Generated by \code{draw_dag}.
#'
#' @returns A tibble containing following columns:
#'
#' @export
adjustment_table <- function(DAG) {
  tibble::tibble(
    outcome = c(rep("Cognition", 3), rep("Affect", 3), "cPA"),
    exposure = c(
      rep("mPA",2), "cPA", # Y = Cognition
      rep("mPA",2), "cPA", # Y = Affect/Mental Health
      "mPA" # Y = c-PA
    ),
    moderator = NA,
    effect = c(
      "total", "direct", rep("total", 2), "direct", rep("total", 2)
    ),
    adjustment_type = c(
      "canonical", "minimal", rep("canonical", 2), "minimal", rep("canonical", 2)
    )
  ) |>
    dplyr::mutate(
      adjustment_set = sapply(seq_len(dplyr::n()), function(i) {
        dag <- DAG |>
          ggdag::ggdag_adjustment_set(
            outcome = outcome[i],
            exposure = ifelse(is.na(moderator[i]), exposure[i], c(exposure[i], moderator[i])),
            effect = effect[i],
            type = adjustment_type[i]
          )
        dag$data |>
          dplyr::distinct(set) |>
          dplyr::pull()
      }) |>
        stringr::str_replace("Affect, ", ""), # dirty trick to get "cPA-free" instead of "direct" effect on Cognition ----
      Y = dplyr::case_when(
        outcome == "Cognition" ~ "{MMSE, FAQ, SA, Z_SA, Delayed_recall_z, TMT_B_z, BNT_30_z, VF_Animals_z}",
        outcome == "Affect" ~ "{GDS15, GAI, Depr, Anx}",
        outcome == "cPA" ~ "{cPA}"
      ),
      X = dplyr::if_else(
        is.na(moderator),
        true = paste(exposure, set2equation(adjustment_set, bracket = TRUE), sep = " * "),
        false = paste(exposure, moderator, set2equation(adjustment_set, bracket = TRUE), sep = " * ")
      ),
      term = dplyr::if_else(
        is.na(moderator),
        true = exposure,
        false = paste0(exposure, ":", moderator)
      ),
      matching = paste0(exposure, " ~ ", set2equation(adjustment_set, bracket = FALSE)) |>
        stringr::str_replace("mPA", "Cosactiw"),
      estimand = "ATC"
    )
}
