#' Set models' specifications
#' 
#' Using tabale of adjustments derived via
#' \code{adjustment_table}, this function
#' prepares model specifications for later
#' fitting.
#' 
#' @param table Tibble. Generated by \code{adjustment_table}.
#' @param faq Character. Should FAQ be treated as binomial
#'   ("count", default) or continuous ("continuous")?
#' 
#' @return A tibble with following columns:
#' 
#' @export
model_specs <- function(table, faq = "count") {
  purrr::map_dfr(seq_len(nrow(table)), function(i) {
    purrr::map_dfr(
      strsplit(unlist(remove_brackets(table[i, "Y"]), use.names = FALSE), ", ", fixed = TRUE)[[1]],
      function(y) data.frame(
        outcome = y,
        exposure = table[i, "exposure"],
        moderator = ifelse(is.na( table[i, "moderator"] ), "1", table[i, "moderator"]),
        term = table[i , "term"],
        likelihood = dplyr::case_when(
          y %in% c("MMSE","Z_SA","GDS15","GAI") ~ "gaussian",
          stringr::str_detect(y, "_z")~ "gaussian",
          y %in% c("SA","cPA","Depr","Anx") ~ "binomial",
          y == "FAQ" & faq == "continuous" ~ "gaussian",
          y == "FAQ" & faq == "count" ~ "binomial"
        ),
        adjusted = paste(y,table[i, "X"], sep = " ~ "),
        unadjusted = paste(y,table[i, "term"], sep = " ~ "),
        analysis = dplyr::case_when( 
          y == "MMSE" ~ 0,
          stringr::str_detect(y, "_z") ~ 2,
          .default = 1
        )
      )
    )
  }) |>
    tidyr::pivot_longer(
      cols = c("adjusted", "unadjusted"),
      names_to = "estimate",
      values_to = "formula"
    )
} 
