#' Table results
#'
#' Computes marginal means and their comparisons of
#' a set of regression models and tables the results.
#'
#' @param fits List. Model fits such as those generated
#'   by \code{fit_models}.
#' @param specs Tibble or data.frame. Contains research
#'   questions operationalisation.
#' @param sets Tibble. Contains variable sets mapping to
#'   table labels. E.g., generated by \code{adjustment_table}.
#'
#' @returns A tibble with formatted marginal means and their
#'   comparisons.
#'
#' @export
stat_test <- function(fits, specs, sets) {
  # Extract & compare marginal means:
  emm <- lapply(rlang::set_names(names(fits)), function(i) {
    compute_means(fits[[i]], subset(specs, estimate == i))
  })
  est <- lapply(rlang::set_names(names(emm)), function(i) {
    extract_means(emm[[i]], subset(specs, estimate == i))
  })
  comp <- lapply(rlang::set_names(names(emm)), function(i) {
    compare_means(emm[[i]], subset(specs, estimate == i))
  })
  # Do residual checks:
  check <- lapply(rlang::set_names(names(fits)), function(i) {
    purrr::map_dbl(rlang::set_names(names(fits[[i]])), function(j) {
      performance::check_residuals(fits[[i]][[j]]) |>
        as.numeric()
    }) |>
      tibble::enframe(name = "fit", value = "p_residual_check") |>
      tidyr::separate(
        fit,
        into = c("y", "x", "m"),
        sep = "\\s*~\\s*|\\s*\\|\\s*",
        remove = TRUE,
        convert = TRUE
      ) |>
      dplyr::mutate(residual_check = dplyr::if_else(
        p_residual_check < .05, "!", ""
      ))
  })
  # Make tables:
  lapply(rlang::set_names(names(fits)), function(t) {
    lapply(rlang::set_names(unique(est[[t]]$x)), function(i) {
      est[[t]] |>
        dplyr::filter(x == i) |>
        tidyr::pivot_wider(values_from = Est, names_from = group, names_prefix = paste0(i, " = ")) |>
        dplyr::left_join(comp[[t]], by = dplyr::join_by(x, y, m, mod)) |>
        dplyr::left_join(check[[t]], by = dplyr::join_by(x, y, m)) |>
        dplyr::mutate(
          Variable = factor(
            sapply(seq_len(dplyr::n()), function(i) {
              unique(sets[stringr::str_detect(sets$Y, y[i]), "outcome"])
            }),
            levels = c("Cognition", "Affect", "cPA"),
            ordered = TRUE
          ),
          sig. = dplyr::if_else(`p value` < .05, "*", ""),
          sig_FDR = bh_adjust(`p value`),
          m = dplyr::if_else(mod == "overall", "", paste0(m," = ",mod)),
          Comparison = paste0(rprint(Comparison, 2), "\n(", rprint(SE, 2),")"),
          #dplyr::across(tidyselect::all_of(c("Comparison", "SE")), \(x) rprint(x, 2)),
          `test. stat.` = rprint(`test. stat.`, 3),
          `raw p` = `p value`,
          `p value` = zerolead(`p value`),
          `s value` = -log2(`raw p`)
        ) |>
        dplyr::select(-mod, -SE) |>
        dplyr::relocate(Variable, .before = 1) |>
        dplyr::rename("Moderator" = "m", "Contrast" = "contrast")
    })
  })
}
